### ISSUE TITLE
Add a twitter button 

### ISSUE THREAD

**Issue by sunilsj99** [sunilsj99/QuoteGenerator#1]
By clicking twitter button quote should be ready to post on your twitter profile.

**Comment by ka3work** [comment]
Can I take this issue?

**Comment by to-var** [comment]
@sunilsj99 I've added a pull request that adds a twitter button, the tweet box that opens will have the quote included in the text.

Here's the pull request:
https://github.com/sunilsj99/QuoteGenerator/pull/12

Here's also a screenshot of the working tweet button
<img width="1521" alt="tweet-button" src="https://user-images.githubusercontent.com/1479977/31867645-16c0d392-b759-11e7-8337-db85182aed48.png">
